"use client";
import { useState } from "react";
import CrudPanel from "@/components/hub/CrudPanel";
import { ACADEMIC_CHANNELS } from "@/lib/hub/module-config.mjs";
const points = { A: 4, "A-": 3.7, "B+": 3.5, B: 3, "B-": 2.7, "C+": 2.5, C: 2, D: 1, E: 0 };
const guide = [["75–100", "A", "4"], ["70–74", "B+", "3.5"], ["66–69", "B", "3"], ["60–65", "C+", "2.5"], ["55–59", "C", "2"], ["40–54", "D", "1"], ["0–39", "E", "0"]];
const weights = [["Blok 3–19, 23–25, 27–28", "OSPE 20 · OSCE 20 · SOCA 20 · MP 30 · Perilaku 10"], ["Blok 1", "SOCA 40 · MP 50 · Perilaku 10"], ["Blok 2", "OSPE 20 · SOCA 30 · MP 40 · Perilaku 10"], ["Blok 20", "OSPE 40 · MP 50 · Perilaku 10"], ["Blok 21 & 22", "OSPE 25 · SOCA 25 · MP 40 · Perilaku 10"], ["Blok 26", "OSCE 25 · SOCA 25 · MP 40 · Perilaku 10"]];
export default function AcademicPanel() {
 const [records, setRecords] = useState([]); const credits = records.reduce((sum, row) => sum + Number(row.credits || 0), 0); const ipk = credits ? records.reduce((sum, row) => sum + Number(row.credits || 0) * (points[row.grade] ?? 0), 0) / credits : 0;
 const bySemester = [...new Set(records.map((row) => row.semester))].map((semester) => { const rows = records.filter((row) => row.semester === semester); const total = rows.reduce((sum, row) => sum + Number(row.credits || 0), 0); return { semester, ip: total ? rows.reduce((sum, row) => sum + Number(row.credits || 0) * (points[row.grade] ?? 0), 0) / total : 0 }; });
 return <><section className="hub-academic-summary"><article><span>IPK / CUMULATIVE</span><strong>{ipk.toFixed(2)}</strong></article><article><span>SKS / CREDITS</span><strong>{credits}</strong></article><article><span>SEMESTERS</span><strong>{bySemester.length}</strong></article>{bySemester.map((item) => <article key={item.semester}><span>IP {item.semester}</span><strong>{item.ip.toFixed(2)}</strong></article>)}</section><section className="hub-academic-guide"><header><span>BLOCK GRADING / AUTOMATIC</span><p>Enter each applicable component score (0–100). The selected block determines its weighting and calculates the final score, grade, IP, and IPK.</p></header><div>{guide.map(([range, grade, point]) => <span key={grade}>{range} <b>{grade}</b> / {point}</span>)}</div><ul>{weights.map(([block, distribution]) => <li key={block}><b>{block}</b><span>{distribution}</span></li>)}</ul></section><CrudPanel {...ACADEMIC_CHANNELS[0]} onRecordsChange={setRecords} /></>;
}
