"use client";

import { Download, Upload } from "lucide-react";
import { requireSupabase } from "@/lib/supabase/client";

const TABLES = ["bank_accounts", "finance_categories", "income_entries", "expenses", "budgets", "subscriptions", "study_topics", "study_exams", "study_flashcards", "hub_projects", "project_tasks", "project_changelog", "vault_documents"];
const download = (name, content, type) => { const url = URL.createObjectURL(new Blob([content], { type })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); };

export default function BackupPanel() {
  const exportData = async (format) => { const client = requireSupabase(); const entries = await Promise.all(TABLES.map(async (table) => { const { data, error } = await client.from(table).select("*"); if (error) throw error; return [table, data || []]; })); const backup = Object.fromEntries(entries); if (format === "json") return download(`4allx-backup-${Date.now()}.json`, JSON.stringify({ version: 1, exported_at: new Date().toISOString(), modules: backup }, null, 2), "application/json"); const rows = entries.flatMap(([table, data]) => data.map((row) => ({ module: table, ...row }))); const columns = [...new Set(rows.flatMap((row) => Object.keys(row)))]; download(`4allx-export-${Date.now()}.csv`, [columns.join(","), ...rows.map((row) => columns.map((key) => JSON.stringify(row[key] ?? "")).join(","))].join("\n"), "text/csv"); };
  const restore = async (event) => { const file = event.target.files?.[0]; if (!file || !window.confirm("Restore adds validated records; existing data is not deleted.")) return; try { const backup = JSON.parse(await file.text()); if (backup?.version !== 1 || typeof backup.modules !== "object") throw new Error("Invalid Personal Hub backup."); const client = requireSupabase(); for (const table of TABLES) { const rows = backup.modules[table]; if (!Array.isArray(rows) || !rows.length) continue; const safeRows = rows.map(({ id, user_id, created_at, updated_at, ...record }) => record); const { error } = await client.from(table).insert(safeRows); if (error) throw error; } alert("Restore completed."); } catch (error) { alert(error.message); } finally { event.target.value = ""; } };
  return <section className="hub-settings-card hub-settings-card--wide"><span>BACKUP / OWNER EXPORT</span><Download aria-hidden="true" /><h2>Portable private data</h2><p>JSON restores use a versioned schema and never delete existing records. Vault file binaries remain in Storage and are not included.</p><div className="hub-backup-actions"><button type="button" onClick={() => exportData("json")}>EXPORT JSON</button><button type="button" onClick={() => exportData("csv")}>EXPORT CSV</button><label><Upload /> RESTORE JSON<input type="file" accept="application/json" onChange={restore} /></label></div></section>;
}
