"use client";
import { useCallback, useEffect, useState } from "react";
import { FileText, FolderUp, Search, Trash2 } from "lucide-react";
import { requireSupabase } from "@/lib/supabase/client";

const safeName = (name) => name.replace(/[^a-zA-Z0-9._-]/g, "-");
export default function VaultPanel() {
 const [docs, setDocs] = useState([]), [query, setQuery] = useState(""), [status, setStatus] = useState(""), [uploading, setUploading] = useState(false);
 const load = useCallback(async () => { try { const { data, error } = await requireSupabase().from("vault_documents").select("*").order("created_at", { ascending: false }); if (error) throw error; setDocs(data || []); } catch (e) { setStatus(e.message); } }, []);
 useEffect(() => { load(); }, [load]);
 const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 26214400) return setStatus("Maximum file size is 25 MB."); setUploading(true); setStatus(""); try { const supabase = requireSupabase(); const { data: { user } } = await supabase.auth.getUser(); if (!user) throw new Error("Sign in required."); const path = `${user.id}/${crypto.randomUUID()}-${safeName(file.name)}`; const { error: storageError } = await supabase.storage.from("document-vault").upload(path, file, { contentType: file.type, upsert: false }); if (storageError) throw storageError; const { error } = await supabase.from("vault_documents").insert({ storage_path: path, file_name: file.name, mime_type: file.type || "application/octet-stream", byte_size: file.size }); if (error) { await supabase.storage.from("document-vault").remove([path]); throw error; } await load(); } catch (e) { setStatus(e.message); } finally { setUploading(false); event.target.value = ""; } };
 const open = async (doc) => { const { data, error } = await requireSupabase().storage.from("document-vault").createSignedUrl(doc.storage_path, 60); if (error) return setStatus(error.message); window.open(data.signedUrl, "_blank", "noopener,noreferrer"); };
 const remove = async (doc) => { if (!window.confirm(`Delete ${doc.file_name}?`)) return; const s = requireSupabase(); const { error } = await s.storage.from("document-vault").remove([doc.storage_path]); if (error) return setStatus(error.message); await s.from("vault_documents").delete().eq("id", doc.id); await load(); };
 const visible = docs.filter((doc) => `${doc.file_name} ${doc.folder} ${(doc.tags || []).join(" ")}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="hub-crud-panel hub-vault"><header className="hub-crud-heading"><div><span>STORAGE / OWNER-ONLY</span><h2>Document Vault</h2><p>Files are never public; previews use short-lived signed URLs.</p></div><label className="hub-vault-upload"><FolderUp /><span>{uploading ? "UPLOADING…" : "UPLOAD FILE"}</span><input type="file" onChange={upload} disabled={uploading} /></label></header><label className="hub-search-input"><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Filter files, folders, or tags" /></label>{status && <p className="hub-data-error">{status}</p>}<div className="hub-record-grid">{visible.map((doc, i) => <article className="hub-record" key={doc.id}><div className="hub-record-index">{String(i + 1).padStart(2, "0")}</div><div className="hub-record-values"><div><span>FILE</span><strong>{doc.file_name}</strong></div><div><span>TYPE</span><strong>{doc.mime_type}</strong></div><div><span>SIZE</span><strong>{Math.ceil(doc.byte_size / 1024)} KB</strong></div></div><div className="hub-record-actions"><button type="button" onClick={() => open(doc)} aria-label={`Preview ${doc.file_name}`}><FileText /></button><button type="button" onClick={() => remove(doc)} aria-label={`Delete ${doc.file_name}`}><Trash2 /></button></div></article>)}</div>{!visible.length && <div className="hub-data-state">NO PRIVATE DOCUMENTS / VAULT READY</div>}</section>;
}
